// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMUAgw21SQFZXnzxijqthz1usHxT_DYtA',
    appId: '1:553281725931:web:ead49444d796802c2aa5ae',
    messagingSenderId: '553281725931',
    projectId: 'docsease-efacc',
    authDomain: 'docsease-efacc.firebaseapp.com',
    storageBucket: 'docsease-efacc.firebasestorage.app',
    measurementId: 'G-DP5SQGZQTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8yimuT1Lesbt2C-haceE4eKl6-V4hlPI',
    appId: '1:553281725931:android:37cffc15c36bd7182aa5ae',
    messagingSenderId: '553281725931',
    projectId: 'docsease-efacc',
    storageBucket: 'docsease-efacc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzkwR45DmLP-qE7eyTUN2pLyf2iLVQ-o',
    appId: '1:553281725931:ios:bde5a88d75ef8c3b2aa5ae',
    messagingSenderId: '553281725931',
    projectId: 'docsease-efacc',
    storageBucket: 'docsease-efacc.firebasestorage.app',
    iosBundleId: 'com.example.docsease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEzkwR45DmLP-qE7eyTUN2pLyf2iLVQ-o',
    appId: '1:553281725931:ios:bde5a88d75ef8c3b2aa5ae',
    messagingSenderId: '553281725931',
    projectId: 'docsease-efacc',
    storageBucket: 'docsease-efacc.firebasestorage.app',
    iosBundleId: 'com.example.docsease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMUAgw21SQFZXnzxijqthz1usHxT_DYtA',
    appId: '1:553281725931:web:092b03312554aac42aa5ae',
    messagingSenderId: '553281725931',
    projectId: 'docsease-efacc',
    authDomain: 'docsease-efacc.firebaseapp.com',
    storageBucket: 'docsease-efacc.firebasestorage.app',
    measurementId: 'G-G3C0CX4CPY',
  );
}
